image: registry.gitlab.com/librespacefoundation/satnogs/satnogs-db:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install --no-cache-dir --no-deps -r requirements-dev.txt
    - cp env-dist .env
    - flake8 .
    - pytest
    - eslint 'db/static/js/*.js'
    - stylelint 'db/static/css/*.css'

docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk --update add py-pip
    - pip install docker-compose
  script:
    - docker-compose build --no-cache --pull
    - |
      [ -z "$CI_REGISTRY_IMAGE" ] || {
          docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
          docker tag satnogs-db:latest $CI_REGISTRY_IMAGE/satnogs-db:$CI_COMMIT_REF_NAME
          docker push $CI_REGISTRY_IMAGE/satnogs-db:$CI_COMMIT_REF_NAME
      }
      [ -z "$DOCKERHUB_PASSWORD" ] || {
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
          docker tag satnogs-db:latest librespace/satnogs-db:$CI_COMMIT_REF_NAME
          docker push librespace/satnogs-db:$CI_COMMIT_REF_NAME
      }
  only:
    refs:
      - master
      - dev

stage:
  stage: deploy
  environment: stage
  only:
   - dev@librespacefoundation/satnogs/satnogs-db
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod -R u=rwX,o=,g= ~/.ssh/
    - echo "$SSH_SERVER_HOSTKEY" > ~/.ssh/known_hosts
    - git checkout dev
    - git push -u ssh://$SERVER_USER@$SERVER_HOST$SERVER_PATH dev

production:
  stage: deploy
  environment: production
  only:
   - master@librespacefoundation/satnogs/satnogs-db
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod -R u=rwX,o=,g= ~/.ssh/
    - echo "$SSH_SERVER_HOSTKEY" > ~/.ssh/known_hosts
    - git checkout master
    - git push -u ssh://$SERVER_USER@$SERVER_HOST$SERVER_PATH master
