version: '3.2'
services:
  db:
    image: 'mariadb:10.3'
    environment:
      MYSQL_DATABASE: 'satnogsdb'
      MYSQL_USER: 'satnogsdb'
      MYSQL_PASSWORD: 'satnogsdb'
      MYSQL_ROOT_PASSWORD: 'toor'
  redis:
    image: 'redis:3.2.8'
  celery:
    build:
      context: '.'
    links:
      - 'db'
      - 'redis'
    environment:
      PYTHONDONTWRITEBYTECODE: '1'
      DATABASE_URL: 'mysql://satnogsdb:satnogsdb@db/satnogsdb'
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    command: ["djangoctl.sh", "develop_celery", "/usr/local/src/satnogs-db"]
    volumes:
      - '.:/usr/local/src/satnogs-db:z'
  web:
    build:
      context: '.'
    image: 'satnogs-db'
    ports:
      - '8000:8000'
    links:
      - 'db'
      - 'redis'
    environment:
      PYTHONDONTWRITEBYTECODE: '1'
      DATABASE_URL: 'mysql://satnogsdb:satnogsdb@db/satnogsdb'
      CACHE_LOCATION: 'redis://redis:6379/0'
    command: ["djangoctl.sh", "develop", "/usr/local/src/satnogs-db"]
    volumes:
      - '.:/usr/local/src/satnogs-db:z'
